import {expect,test} from 'playwright/test'
test.use({channel:'chrome'})
test.beforeEach(async({page})=>{
  await page.route('**/api/track',route=>route.fulfill({json:{ok:true}}))
  await page.route('**/api/contact',route=>route.fulfill({json:{available:false}}))
  await page.route('**/api/chat',route=>{
    const body=route.request().postDataJSON()
    if(body.mode) return route.fulfill({json:{reply:'I would like to discuss an OCR project.'}})
    const text="[Duy's agent]\n\nThe most handsome — according to this biased bunny. Here are his photos. [[card:profile-portrait]] [[card:life-leaf-portrait]] [[card:life-outside]] [Life](/life) [bad](javascript:alert(1))"
    return route.fulfill({contentType:'text/event-stream',body:`data: ${JSON.stringify({delta:text})}\n\nevent: done\ndata: [DONE]\n\n`})
  })
})
test('rich terminal replies preview actual photos, reject unsafe links, preserve draft on navigation',async({page})=>{
  await page.goto('/')
  const input=page.locator('#terminal-chat-input')
  await input.fill('Show me photos of Duy')
  await input.press('Enter')
  const window=page.locator('[data-terminal-window]')
  await expect(window.locator('[data-chat-card]')).toHaveCount(4)
  await expect(window.locator('a[href^="javascript:"]')).toHaveCount(0)
  await window.getByRole('button',{name:'Preview image: Duy, in person'}).click()
  await expect(page.locator('dialog[open].chat-media-dialog')).toBeVisible()
  await page.getByRole('button',{name:'Close preview'}).click()
  await input.fill('my unsent follow-up')
  await window.locator('a.chat-inline-link[href="/life"]').click()
  await expect(page).toHaveURL(/\/life$/)
  await expect(page.getByRole('button',{name:'Resume chat'})).toBeVisible()
  await page.getByRole('button',{name:'Resume chat'}).click()
  await expect(page).toHaveURL(/#terminal-chat/)
  await expect(page.locator('#terminal-chat-input')).toHaveValue('my unsent follow-up')
  await expect(page.locator('[data-terminal-window]')).toContainText('The most handsome')
})
test('quick-chat renders the same photo cards and double-click resumes full chat',async({page})=>{
  await page.goto('/life')
  const pet=page.locator('.gracie-launcher')
  await pet.click()
  await page.locator('#gracie-input').fill('Show me photos of Duy')
  await page.locator('#gracie-input').press('Enter')
  await expect(page.locator('#gracie-chat [data-chat-card]')).toHaveCount(4)
  await pet.dblclick()
  await expect(page).toHaveURL(/#terminal-chat/)
  await expect(page.locator('[data-terminal-window]')).toContainText('The most handsome')
})
test('terminal fills viewport, outside click and reset restore compact size on mobile and desktop',async({page})=>{
  for(const width of [375,1280]){
    await page.setViewportSize({width,height:812})
    await page.goto('/')
    await page.getByRole('button',{name:'Maximize window',exact:true}).click()
    const dialog=page.locator('[data-terminal-window][data-maximized="true"]')
    await expect(dialog).toBeVisible()
    const box=await dialog.boundingBox()
    expect(box?.width).toBeGreaterThan(width*.85)
    expect(box?.height).toBeGreaterThan(730)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.mouse.click(4,4)
    await expect(page.locator('[data-maximized="true"]')).toHaveCount(0)
    await page.getByRole('button',{name:'Maximize window',exact:true}).click()
    await page.getByRole('button',{name:'Reset window size'}).click()
    await expect(page.locator('[data-maximized="true"]')).toHaveCount(0)
  }
})
test('secret discovery and pet discovery remain separate; trigger needs the name twice',async({page})=>{
  await page.clock.install()
  await page.goto('/life')
  await expect(page.locator('.gracie-launcher')).toBeVisible()
  await page.clock.runFor(30000)
  await expect(page.getByRole('status',{name:'Hidden feature hint'})).toBeVisible()
  await page.clock.runFor(5000)
  await expect(page.getByRole('status',{name:'Hidden feature hint'})).toContainText('leduy leduy')
  await page.getByRole('button',{name:'Dismiss hidden feature hint'}).click()
  await page.clock.runFor(60000)
  await expect(page.getByRole('complementary',{name:'Pets suggestion'})).toBeVisible()
  await page.keyboard.type('leduy')
  await expect(page.getByRole('heading',{name:'🎁 Mystery Box'})).toHaveCount(0)
  await page.keyboard.type(' leduy')
  await expect(page.getByRole('heading',{name:'🎁 Mystery Box'})).toBeVisible()
})
test('compose shows an honest free mail-app fallback while direct delivery is unconfigured',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:/Send to Duy/}).first().click()
  await expect(page.getByRole('link',{name:'Open email app ↗'})).toBeVisible()
  await expect(page.getByRole('link',{name:'Open email app ↗'})).toHaveAttribute('href',/mailto:levduyit@gmail.com/)
})

test('arcade links select a known game and ignore unknown identifiers',async({page})=>{
  await page.route('**/games/**',route=>route.fulfill({contentType:'text/html',body:'<p>Playable test world</p>'}))
  await page.goto('/arcade?game=last-beacon')
  await expect(page.locator('dialog[open] iframe')).toHaveCount(1)
  await page.goto('/arcade?game=missing-private-route')
  await expect(page.locator('dialog[open]')).toHaveCount(0)
})
