import {expect,test} from 'playwright/test'
test.use({channel:'chrome'})
test.beforeEach(async({page})=>{
  await page.route('**/api/track',route=>route.fulfill({json:{ok:true}}))
  await page.route('**/api/contact',route=>route.fulfill({json:{available:false}}))
})
test('research cycles at 30 foreground seconds, retains remaining time while hovered, manual selection pauses',async({page})=>{
  await page.clock.install()
  await page.goto('/blog')
  // This test advances several minutes of the carousel clock; scene rendering is verified separately.
  await page.addStyleTag({content:'[data-cover-model]{display:none}'})
  const carousel=page.locator('[data-featured-carousel]')
  const current=carousel.locator('[data-featured-slide]')
  await expect(current).toHaveAttribute('data-featured-slide','research-0')
  await page.mouse.move(1,1)
  await page.clock.fastForward(10000)
  await carousel.hover()
  await page.clock.fastForward(35000)
  await expect(current).toHaveAttribute('data-featured-slide','research-0')
  await page.mouse.move(1,1)
  await page.clock.fastForward(19000)
  await expect(current).toHaveAttribute('data-featured-slide','research-0')
  await page.clock.runFor(1500)
  await expect(current).toHaveAttribute('data-featured-slide','research-1')
  await carousel.getByRole('button',{name:'Next slide',exact:true}).click()
  await expect(current).toHaveAttribute('data-featured-slide','research-2')
  await expect(carousel.getByRole('button',{name:'Resume slideshow'})).toBeVisible()
  await page.clock.fastForward(60000)
  await expect(current).toHaveAttribute('data-featured-slide','research-2')
  await expect(carousel.locator('img')).toHaveCount(0)
  await expect(page.locator('main article')).toHaveCount(5)
})
test('cinema browses distinct covers, keeps the original large model and leaves film notes below',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.setViewportSize({width:375,height:812})
  await page.clock.install()
  await page.goto('/movie')
  const carousel=page.locator('[data-featured-carousel]')
  await expect(carousel).toContainText('1 / 4')
  await expect(carousel.locator('[data-cover-model="cinema-reel"]')).toHaveAttribute('data-model-ready','true')
  await expect(carousel.locator('[data-model-motion="static"]')).toHaveCount(1)
  await expect(carousel.locator('img')).toHaveCount(0)
  await page.clock.fastForward(60000)
  await expect(carousel).toContainText('1 / 4')
  await expect(carousel.getByRole('button',{name:'Pause slideshow'})).toHaveCount(0)
  await carousel.getByRole('button',{name:'Next slide'}).click()
  await expect(carousel.locator('[data-featured-slide]')).toHaveAttribute('data-featured-slide','cinema-1')
  await expect(carousel).toContainText('2 / 4')
  await expect(carousel.locator('[data-cover-variant="paired-reels"]')).toHaveAttribute('data-model-ready','true')
  await carousel.getByRole('button',{name:'Next slide'}).click()
  await expect(carousel.locator('[data-cover-variant="projector"]')).toHaveAttribute('data-model-ready','true')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
  await page.locator('a[href="/movie/oppenheimer"]').first().click()
  await expect(page).toHaveURL(/\/movie\/oppenheimer$/)
})
test('English identity and verified web citations survive Life navigation and companion resume',async({page})=>{
  await page.route('**/api/chat',route=>route.fulfill({contentType:'text/event-stream',body:`event: sources\ndata: ${JSON.stringify({sources:[{title:'Official guide',url:'https://docs.example.com/rag'},{title:'Bad',url:'https://127.0.0.1/private'}]})}\n\ndata: ${JSON.stringify({delta:"[Michael's agent]\n\nHybrid retrieval combines lexical and vector search. [Guide](https://docs.example.com/rag) [Life](/life) [fake](https://evil.example)"})}\n\nevent: done\ndata: [DONE]\n\n`}))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Michael Le.'})).toBeVisible()
  const input=page.locator('#terminal-chat-input')
  await input.fill('Explain hybrid RAG with sources')
  await input.press('Enter')
  const terminal=page.locator('[data-terminal-window]')
  await expect(terminal.locator('[data-web-sources] a')).toHaveCount(1)
  await expect(terminal.locator('a[href="https://evil.example"]')).toHaveCount(0)
  await terminal.locator('a[href="/life"]').first().click()
  await page.getByRole('button',{name:'Resume chat'}).click()
  await expect(page.locator('[data-terminal-window] [data-web-sources] a')).toHaveAttribute('href','https://docs.example.com/rag')
})
