import {test,expect} from 'playwright/test'

const base=process.env.OBSERVABILITY_TEST_URL || 'http://localhost:3007'
test.skip(!process.env.OBSERVABILITY_TEST_URL,'Requires isolated Redis namespace and local admin test credentials; see docs/email-setup.md')

test('actual server persists streamed chat, pet clicks and contact text into owner inbox',async({page},testInfo)=>{
  const errors:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  await page.goto(`${base}/`)
  const input=page.locator('#terminal-chat-input')
  await expect(input).toBeVisible()
  const chat=page.waitForResponse(response=>response.url().endsWith('/api/chat') && response.request().postData()?.includes('handsome')===true)
  await input.fill('Is Michael handsome?')
  await input.press('Enter')
  const response=await chat
  expect(response.status()).toBe(200)
  await expect(page.getByText('The most handsome',{exact:false}).last()).toBeVisible()
  await expect(page.locator('[data-chat-storage-notice]').first()).toBeVisible()
  await page.goto(`${base}/life`)
  await page.locator('.gracie-launcher').click()
  await expect(page.locator('#gracie-chat')).toBeVisible()
  const quick=page.locator('#gracie-chat textarea')
  await quick.fill('Is Michael handsome?')
  const quickResponse=page.waitForResponse(response=>response.url().endsWith('/api/chat'))
  await page.locator('[data-track="pet:send-chat"]').click()
  expect((await quickResponse).status()).toBe(200)
  await expect(page.locator('#gracie-chat').getByText('The most handsome',{exact:false}).last()).toBeVisible()
  await expect(quick).toBeEnabled()
  await page.goto(`${base}/`)
  await page.route('**/api/chat',async route=>{
    const data=route.request().postDataJSON()
    if(data.mode==='compose') await route.fulfill({json:{reply:'Production-build verification: this contact text must be visible in the private owner inbox.'}})
    else await route.continue()
  })
  await page.getByRole('button',{name:/Send to (Michael|Duy)/}).first().click()
  await page.locator('input[type="email"]').fill('owner-verification@example.com')
  await expect(page.locator('[data-track="contact:send"]')).toBeEnabled()
  const contact=page.waitForResponse(response=>response.url().endsWith('/api/contact') && response.request().method()==='POST')
  await page.locator('[data-track="contact:send"]').click()
  const receipt=await contact
  expect(receipt.status()).toBe(202)
  expect((await receipt.json()).status).toBe('stored')
  await expect(page.getByText('Your message is saved in Michael’s website inbox.',{exact:false})).toBeVisible()
  expect((await page.request.get(`${base}/api/admin/conversations`)).status()).toBe(404)
  const login=await page.request.post(`${base}/api/admin/login`,{data:{passphrase:'local-verification-only'}})
  expect(login.status()).toBe(200)
  const listed=await page.request.get(`${base}/api/admin/conversations`)
  expect(listed.status()).toBe(200)
  const records=(await listed.json()).records
  expect(records.length).toBeGreaterThan(0)
  const selected=records.find((record:{preview:string})=>record.preview.includes('Production-build verification'))
  expect(selected).toBeTruthy()
  const turns=(await (await page.request.get(`${base}/api/admin/conversations?id=${selected.id}`)).json()).records
  expect(turns.filter((turn:{mode:string;status:string})=>turn.mode==='chat' && turn.status==='complete').length).toBeGreaterThanOrEqual(2)
  expect(turns.some((turn:{email:string;error:string})=>turn.email==='owner-verification@example.com' && turn.error==='delivery_unconfigured')).toBe(true)
  await page.goto(`${base}/admin`)
  await expect(page.getByRole('heading',{name:'Conversations & contact inbox'})).toBeVisible()
  await page.locator('[data-admin-conversations] button').filter({hasText:'Production-build verification'}).first().click()
  await expect(page.getByText('From: owner-verification@example.com',{exact:false})).toBeVisible()
  await expect(page.locator('[data-admin-conversations]').getByText('The most handsome',{exact:false}).first()).toBeVisible()
  const summary=await (await page.request.get(`${base}/api/admin/summary?range=all`)).json()
  expect(summary.interactions.chatQuestions).toBeGreaterThanOrEqual(2)
  expect(summary.interactions.contactSubmissions).toBeGreaterThan(0)
  expect(summary.interactions.topButtons.some((button:{label:string})=>button.label==='pet:launcher')).toBe(true)
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export full conversation'}).click()
  const file=await (await download).path()
  const {readFile}=await import('node:fs/promises')
  const exported=JSON.parse(await readFile(file!,'utf8'))
  expect(exported.records.length).toBeGreaterThanOrEqual(3)
  await page.screenshot({path:testInfo.outputPath('admin-conversation-review.png'),fullPage:false})
  expect(errors).toEqual([])
})

test('DNT prevents detailed chat analytics while the voluntary contact inbox remains available',async({browser})=>{
  const context=await browser.newContext({extraHTTPHeaders:{'x-portfolio-dnt':'1'}})
  const page=await context.newPage()
  const login=await page.request.post(`${base}/api/admin/login`,{data:{passphrase:'local-verification-only'}})
  expect(login.status()).toBe(200)
  const before=await (await page.request.get(`${base}/api/admin/conversations`)).json()
  const response=await page.request.post(`${base}/api/chat`,{data:{conversationId:crypto.randomUUID(),turnId:crypto.randomUUID(),messages:[{role:'user',content:'Is Michael handsome?'}],stream:true}})
  expect(response.status()).toBe(200)
  const after=await (await page.request.get(`${base}/api/admin/conversations`)).json()
  expect(after.total).toBe(before.total)
  const contact=await page.request.post(`${base}/api/contact`,{data:{requestId:crypto.randomUUID(),email:'dnt-verification@example.com',subject:'DNT contact verification',message:'This voluntary contact must still be saved without visitor analytics.'}})
  expect(contact.status()).toBe(202)
  const withContact=await (await page.request.get(`${base}/api/admin/conversations`)).json()
  expect(withContact.total).toBe(after.total+1)
  await context.close()
})
